openapi: 3.0.0
info:
  version: 1.0.0
  title: Flask Recipe
  description: A simple api documentation for the flask recipe.
  
components:
  securitySchemes:
    cookieAuth:         # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: session  # cookie name
      
  schemas:
    User:
      type: object
      required:
        - username
      properties:
        id:
          type: integer
          example: 1
        fullname:
          type: string
          example: Eduardo Rodríguez
        username:
          type: string
          example: edmarola
        
  responses:
    422Error:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            type: object 
            properties:
              errors:
                type: object
                properties:
                  json | query:
                    type: object
                    properties:
                      field_name:
                        type: array
                        items:
                          type: string
                          example: Error message
                      

security:
  - cookieAuth: []
  
paths:
  /auth/login:
    post:
      requestBody:
        required: true
        description: A JSON object containing the username and password.
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: edmarola
                password:
                  type: string
                  example: 1234
              
      security: []
      description: Given a valid username and password, a cookie with the session info is returned.              
      responses:
        '200':
          description: >
            Successfully authenticated.
            The session ID is returned in a cookie named `session`. You need to include this cookie in subsequent requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          headers:
            Set-Cookie:
              schema: 
                type: string
                example: session=abcde12345; Path=/; HttpOnly
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:           
                  error:
                    type: string
                    example: Invalid credentials
        '422':
          $ref: '#/components/responses/422Error'
      tags:
        - Authentication
          